### PR TITLE
Added namespace to crisp.php

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by valeriansaliou** [comment]
@mywaystar sounds good for you?

**Comment by ghost** [comment]
I need this to integrate into my larvel project. Maybe you can help me on that?

**Comment by baptistejamin** [comment]
What is the issue @kris120197 with Laravel?

**Comment by ghost** [comment]
I want to include it not like autoload.php but like "use {namespace}".

**Comment by baptistejamin** [comment]
Merging this will produce a breaking change for people using the autoload feature.

**Comment by ghost** [comment]
How can I use my fork directory as composer package?

**Comment by baptistejamin** [comment]
Please check https://stackoverflow.com/questions/12954051/use-php-composer-to-clone-git-repo

**Comment by ghost** [comment]
I'll try. Thanks. Sorry for that. Have a nice day.

**Pull request closed without merging**
